language: node_js
node_js:
  - "8.1"
sudo: false
before_install:
  - rvm install 2.2.2
  - ./tool/before_install.sh
script: ./tool/travis.sh


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master